version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 99
    groups:
      github-action-dependencies:
        patterns:
          - "*"
  - package-ecosystem: "pip"
    directory: "/.github/workflows"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 99
    groups:
      workflows-dependencies:
        patterns:
          - "*"
  - package-ecosystem: "pip"
    directory: "/generated/python"
    schedule:
      interval: "monthly"
    versioning-strategy: lockfile-only
    allow:
      - dependency-type: "all"
    open-pull-requests-limit: 99
    groups:
      python-dependencies:
        patterns:
          - "*"
  - package-ecosystem: maven
    directory: "/generated/java"
    reviewers:
      - "statisticsnorway/reg-freg-developers"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 99
    groups:
      java-dependencies:
        patterns:
          - "*"
