# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python tests

on:
  push:
    paths:
      - "generated/python/datadoc_model/**"
      - ".github/workflows/test-python.yml"

permissions:
  contents: read
  issues: write
  pull-requests: write

jobs:
  run-unit-tests:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./generated/python/datadoc_model
    steps:
      - uses: actions/checkout@v5
      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          version: "0.7.2"
          enable-cache: true

      - name: Run tests
        run: |
          uv run pytest -v --cache-clear
