# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python tests

on:
  push:
    paths:
      - "generated/python/datadoc_model/**"
      - ".github/workflows/test-python.yml"

permissions:
  contents: read
  issues: write
  pull-requests: write

jobs:
  run-unit-tests:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./generated/python/datadoc_model
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v1
        with:
          python-version: "3.11"
      - uses: Gr1N/setup-poetry@v8
      - uses: actions/cache@v4
        with:
          path: ~/.cache/pypoetry/virtualenvs
          key: ${{ runner.os }}-poetry-${{ hashFiles('poetry.lock') }}
      - name: Print Poetry version
        run: poetry --version
      - name: Install dependencies
        run: |
          poetry install
      - name: Run unit tests
        run: |
          poetry run pytest -v --cache-clear
